server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: player-service
          uri: http://localhost:8082
          predicates:
            - Path=/players/**
        - id: game-service
          uri: http://localhost:8083
          predicates:
            - Path=/games/**
        - id: card-service
          uri: http://localhost:8084
          predicates:
            - Path=/cards/**
        - id: session-service
          uri: http://localhost:8085
          predicates:
            - Path=/sessions/**
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/notifications/**

      default-filters:
        - TokenRelay

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: hKfYbV1L1LwzFX2Yw8hEHyTj3E4xjV5SyJ6eR3Jg+oE=

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: hKfYbV1L1LwzFX2Yw8hEHyTj3E4xjV5SyJ6eR3Jg+oE=

# Eureka
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/